name: CoVItaly
description: An app that fetches data from the repository of the Protezione Civile Italiana

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  url_launcher: ^5.4.2
  json_annotation: ^3.0.1
  built_collection: ^4.3.2
  built_value: ^7.0.4
  http: ^0.12.0+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.4
  json_serializable: ^3.2.5
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
